### ISSUE TITLE
Create a package and activity for Badminton

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/Android-ScorerApp#18]
Similar to basketball and volleyball create a activity and package for badminton.

**Comment by Sarthak2601** [comment]
Working on it.

**Comment by chanmol1999** [comment]
Work on one issue at a time @Sarthak2601 .
Do look at the updated rules in README.

**Comment by Sarthak2601** [comment]
@chanmol1999 All the 3 issues are inter-related and can be done in 1 PR. That's why commented together.

**Comment by chanmol1999** [comment]
Basically these issues were made for the new contributors in the repository.
So it would be better if you abide by the rules.You can even work on all 3 issues but one by one.

**Comment by Sarthak2601** [comment]
@chanmol1999 Okay sure.

**Comment by Mehulipal** [comment]
Can I work on it?
