### ISSUE TITLE
Updating Readme.md with Images of App

### ISSUE THREAD

**Issue by SAITARUN55** [NJACKWinterOfCode/Android-ScorerApp#24]
@chanmol1999 bro...Will work on this issue...please do assign me for this

**Comment by shash137** [comment]
I want to work on this @chanmol1999

**Comment by SAITARUN55** [comment]
I had already started working on this...will raise a PR by tomorrow

**Comment by chanmol1999** [comment]
@SAITARUN55 status?
otherwise, I should assign this to anyone else.

**Comment by SAITARUN55** [comment]
Completed @chanmol1999
