### ISSUE TITLE
Authentications

### ISSUE THREAD

**Issue by Sarthak2601** [NJACKWinterOfCode/Android-ScorerApp#39]
*Firebase Integration 
*Sign up using Email/Password 
*Sign in using - 
1. Email/Password 
2. Google 
3. Facebook

**Comment by Sarthak2601** [comment]
Working on it.

**Comment by chanmol1999** [comment]
@Sarthak2601  Any reason for this authentication?
Like I don't think we should keep any kind of authentication in the app.

**Comment by Sarthak2601** [comment]
@chanmol1999 In today's era almost every app(organisation) tries to keep a track of user data like their name and email. It not only provides us with a well organised record of our users but also provides proper statistics for further development of the App. Basically it enhances the chances of growth of the app in the future.

**Comment by chanmol1999** [comment]
@Sarthak2601 their is no such thing in this app which requires track of user data.
It is a simple scorer app instead for that development of the app we can have a feedback section in the app.There is no need of unneccesary authentication in the app.
