### ISSUE TITLE
Improve UI of Main Activity

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/Android-ScorerApp#4]

**Comment by Sarthak2601** [comment]
What all improvements are required ?

**Comment by Sarthak2601** [comment]
What kind of improvements to the UI of Main Activity are required ?

**Comment by chanmol1999** [comment]
The UI of the main activity has to be redesigned. It is open for suggestions.

**Comment by Ashish0077** [comment]
How about this?
#7

**Comment by chanmol1999** [comment]
Anyone working on this @Ashish0077 @Sarthak2601 ?

**Comment by Kavya-24** [comment]
I am working.

**Comment by chanmol1999** [comment]
Go ahead @Kavya-24

**Comment by Sarthak2601** [comment]
Can i work on it ?

**Comment by chanmol1999** [comment]
Go ahead @Sarthak2601

**Comment by archit2603** [comment]
Working on it.

**Comment by chanmol1999** [comment]
Solved by Archit .
You can work on this if you have a better idea.
