### ISSUE TITLE
Lack of uniformity in the UI of the app

### ISSUE THREAD

**Issue by archit342000** [NJACKWinterOfCode/Android-ScorerApp#46]

**Comment by archit342000** [comment]
Working on it.

**Comment by archit2603** [comment]
![Screenshot_2019-12-12-08-58-06-716_com example anmol courtcounter](https://user-images.githubusercontent.com/54908590/70680294-ce137600-1cbd-11ea-9233-6a954539b0e5.jpg)

![Screenshot_2019-12-12-08-58-15-205_com example anmol courtcounter](https://user-images.githubusercontent.com/54908590/70680327-eedbcb80-1cbd-11ea-9165-576e894e8b6c.jpg)

Basketball and Volleyball revamped UI.

**Comment by chanmol1999** [comment]
Ya, I was in concern of this too.
@archit2603 Try to create a uniform UI for all games.
Also, design a theme for the whole app.

**Comment by archit342000** [comment]
![Screenshot_2019-12-12-15-44-22-116_com example anmol courtcounter](https://user-images.githubusercontent.com/54908590/70703610-7ba27b80-1cf6-11ea-94ef-50488a1be049.jpg)
![Screenshot_2019-12-12-15-44-14-758_com example anmol courtcounter](https://user-images.githubusercontent.com/54908590/70703633-84934d00-1cf6-11ea-9e09-c05f46ca20be.jpg)
![Screenshot_2019-12-12-15-44-18-043_com example anmol courtcounter](https://user-images.githubusercontent.com/54908590/70703641-865d1080-1cf6-11ea-9a25-2034b347e84d.jpg)

Current status
