### ISSUE TITLE
Add menu option to display results of last 5 matches

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/Android-ScorerApp#5]
Add menu option to display results of the last 5 matches for basketball.

**Comment by anubhav11march** [comment]
I would like to work in this.

**Comment by chanmol1999** [comment]
Go ahead @anubhav11march

**Comment by refactor-droidyy** [comment]
@chanmol1999 is someone still working on this issue if not can I work on it?

**Comment by chanmol1999** [comment]
Ya I don't think @anubhav11march is working now .
You can go ahead @refactor-droidyy .

**Comment by Sarthak2601** [comment]
Can I work on it? @chanmol1999
