### ISSUE TITLE
Bugs in Cricket Scoring and addition of some features.

### ISSUE THREAD

**Issue by archit342000** [NJACKWinterOfCode/Android-ScorerApp#51]
* No option to select format of the match (T20, ODI or Test)
* No limit for number of wickets fallen.
* No provision of wide or no ball.
* Both teams can score at the same time.
* No provision for display of result.
* Addition of provision for super over (for T20s).
* Option to select which team bats first.
* Day system (for Test matches).

**Comment by archit342000** [comment]
Working on it.

**Comment by chanmol1999** [comment]
Go ahead @archit2603
