### ISSUE TITLE
Reflect red and yellow card in football simultaneously

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/Android-ScorerApp#63]
Currently red and yellow card doesn't reflect simultaneously on the scoreboard.

**Comment by jay24rajput** [comment]
Hey can I work on this issue??

**Comment by chanmol1999** [comment]
Go ahead @jay24rajput

**Comment by jay24rajput** [comment]
Hey, Can you please elaborate on the issue. Do you want the toast to be at the same time?

**Comment by chanmol1999** [comment]
@jay24rajput See current scenario is although red and yellow cards issued to a team are reflected in the final scoreboard.
I want them to be reflected on the scoreboard as per the time they are issued.
