### ISSUE TITLE
Complete the Volleyball activity

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/Android-ScorerApp#8]
- [ ] Implement UI of Volleyball Activity
- [ ] Implement point system for Volleyball game

**Comment by Ashish0077** [comment]
can i work on this?

**Comment by chanmol1999** [comment]
Yes you can proceed

**Comment by saumya1singh** [comment]
@chanmol1999  can we create our own issues and start working on them because for now number of  issues available are quite less? Are there points for creating new issues ?

**Comment by chanmol1999** [comment]
> @chanmol1999 can we create our own issues and start working on them because for now number of issues available are quite less? Are there points for creating new issues ?

Yes of course.
There are 2 points for creating a legitimate issue.

**Comment by Ashish0077** [comment]
@chanmol1999 
please review #11

**Comment by Sarthak2601** [comment]
Can i work on it ?

**Comment by Sarthak2601** [comment]
Working on it.

**Comment by Ashish0077** [comment]
i'm already working on it!! @Sarthak2601
