### ISSUE TITLE
BUG - Badminton Activity 

### ISSUE THREAD

**Issue by Sarthak2601** [NJACKWinterOfCode/Android-ScorerApp#88]
Expected Behaviour - Alert dialog buttons should be displayed in the Result Alert Box. 

Current Behaviour - Only the result is displayed, no buttons. 

Possible Solution(s) - Adding buttons to the AlertDialog Box. 

Would you like to work on this issue? Yes.

**Comment by chanmol1999** [comment]
This should have been  fixed in #69. @Sarthak2601

**Comment by Sarthak2601** [comment]
@chanmol1999 It was fixed in #69 but it occurred again. Thus became a bug. I think it should be considered. 
I had fixed everything in #69 you can check the screenshots attached there. This bug has happened after that.

**Comment by chanmol1999** [comment]
@Sarthak2601 This bug is because you didnot set postive and negative button in dialog when gameB>1 .
Please check ......
